### ISSUE TITLE
Implement the different "styles" of results

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-learn-search-components#6]
I'm coming at this from a very nieve perspective so apologies if my summary or understanding of what is currently happening. Also for context, the reason I'm tackling this now is that the Guides app seems to have started returning results for the API docs. I don't know if this is what we were expecting but there is an issue to discuss that aspect here: https://github.com/ember-learn/guides-app/issues/51

In my manual testing, I have identified that there are different structures of search results coming back from Algolia. If I type `test` into the search it looks like we get 2 groups of **non-guides** search results back i.e. Packages and Classes.

<img width="608" alt="screen shot 2018-03-29 at 09 39 04" src="https://user-images.githubusercontent.com/594890/38079505-f5978940-3336-11e8-933b-af18e955bd73.png">

The structure of this response seems to have 2 "types" of responses from Algolia, each of which has 2 "levels" of hierarchy (I think that's how to describe it)

```
{
  "hits": [{
    "hierarchy": {
      "lvl2": null,
      "lvl3": null,
      "lvl0": "Packages",
      "lvl1": "Package ember-testing",
      "lvl6": null,
      "lvl4": null,
      "lvl5": null
    },
    ...
  },
  ...,
  {
    "hierarchy": {
      "lvl2": null,
      "lvl3": null,
      "lvl0": "Classes",
      "lvl1": "Class Ember.Test.Adapter",
      "lvl6": null,
      "lvl4": null,
      "lvl5": null
    },
    ...
  },
  ...,
  ]
}
```

If you continue to type (working towards "testing") you get this set of results: 

<img width="610" alt="screen shot 2018-03-29 at 09 39 13" src="https://user-images.githubusercontent.com/594890/38079957-1a19bf4e-3338-11e8-8a08-61f0810d771c.png">

where you can clearly see that the guides results are now being added. This response structure is more like this:

```
{
  "hits": [{
    "hierarchy": {
      "lvl2": null,
      "lvl3": null,
      "lvl0": "Packages",
      "lvl1": "Package ember-testing",
      "lvl6": null,
      "lvl4": null,
      "lvl5": null
    },
    ...
  }, {
    "hierarchy": {
      "lvl2": "Testing Components",
      "lvl3": null,
      "lvl0": "Guides",
      "lvl1": "Testing",
      "lvl6": null,
      "lvl4": null,
      "lvl5": null
    },
    ...
  },
  ...],
}
```

Assumptions: 
- there are only 3 "styles" of results returned for Guides Search
	- Packages 
	- Classes
	- Guides
- we can use the URL that is returned in all 3 cases
	- I understand that there are chances that the URLs could be broken but I'm talking about just to get the same behaviour as the currently deployed guides' search
- Packages and Classes only need to display the information in `lvl1` i.e. they don't need to combine items like the guides does

**Comment by jaredgalanis** [comment]
We're closing this because the only repos which consume this tool are archived/deprecated. Thank you for your interest in contributing to the Ember project!
